[workspace]
resolver = "2"
members = [
    "crates/momus-core",
    "crates/momus-mock",
    "crates/momus-convert",
    "crates/momus-cli",
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/jlcoulter/momus"
homepage = "https://github.com/jlcoulter/momus"
documentation = "https://github.com/jlcoulter/momus#readme"
readme = "README.md"
