package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"github.com/jlcoulter/momus/internal/home"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// initializeViper wires viper into the config used by a command. It sets up
// config file discovery and environment variable binding, reads the config
// file, and merges values into cfg with the following precedence (highest
// first):
//
//  1. explicitly-set CLI flags
//  2. environment variables (MOMUS_ prefix)
//  3. config file (--config path, ./momus.toml, or ~/.momus/config.toml)
//  4. flag defaults (already applied to cfg by cobra)
//
// CLI flags are bound directly to cfg fields by cobra, so this function must
// not let viper clobber values the user set explicitly on the command line.
// It snapshots those fields before unmarshaling and restores them afterwards.
func initializeViper(cfg *config, cmd *cobra.Command) error {
	explicit := captureFlagValues(cfg, cmd)
	if err := configureViper(cfg); err != nil {
		return err
	}
	if err := viper.ReadInConfig(); err != nil {
		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
			return fmt.Errorf("read config file: %w", err)
		}
		// Config file not found; defaults and CLI flags still apply.
	}
	if err := viper.Unmarshal(cfg); err != nil {
		return fmt.Errorf("parse config: %w", err)
	}
	restoreExplicitFlagValues(cfg, explicit)
	return nil
}

// userConfigPath is the per-user config file (relative to $HOME) that is
// auto-initialised with a placeholder template on first run.
const userConfigPath = ".momus/config.toml"

// configureViper sets up viper and resolves which config file to load.
//
// Precedence (highest first):
//  1. the --config flag path
//  2. ./momus.toml in the working directory
//  3. $HOME/.momus/config.toml (auto-initialised on first run if missing)
//
// Environment variables (MOMUS_ prefix) and CLI flags remain the highest and
// lowest priority sources respectively, on top of whatever config file is
// loaded.
func configureViper(cfg *config) error {
	// Environment variable binding applies regardless of where the config file
	// lives. AutomaticEnv alone is not consulted by viper.Unmarshal, so each
	// key is explicitly bound to its MOMUS_* variable.
	viper.SetEnvPrefix("MOMUS")
	viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_"))
	viper.AutomaticEnv()

	switch {
	case cfg.ConfigFile != "":
		viper.SetConfigFile(cfg.ConfigFile)
	case fileExists("momus.toml"):
		viper.SetConfigFile("momus.toml")
	default:
		homeConfig := home.ConfigPath()
		if err := ensureHomeConfig(homeConfig); err != nil {
			return err
		}
		viper.SetConfigFile(homeConfig)
	}

	return bindAllEnv()
}

// fileExists reports whether path exists and is a regular file.
func fileExists(path string) bool {
	fi, err := os.Stat(path)
	return err == nil && !fi.IsDir()
}

// ensureHomeConfig creates $HOME/.momus/config.toml with placeholder content
// when it does not yet exist.
func ensureHomeConfig(path string) error {
	if fileExists(path) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create config dir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(homeConfigTemplate), 0o600); err != nil {
		return fmt.Errorf("write home config %s: %w", path, err)
	}
	return nil
}

// homeConfigTemplate is the placeholder written to $HOME/.momus/config.toml on
// first run.
const homeConfigTemplate = `# Momus user configuration.
# This file was auto-generated by momus. Uncomment and edit lines as needed.
# The --config flag or a ./momus.toml in the working directory takes precedence.

# Global
# debug = false

# Package resolution
# deps_dir = ""
# download_dir = ""
# conflict_policy = "root-wins"

# Output
# output_path = ""
# html_report = ""
# output_dir = "" # default: $HOME/.momus/output (versioned on replacement)

# Derivation scoping
# include_resource_types = []
# include_profile_urls = []
# exclude_path_prefixes = []
# exclude_extension_urls = []
# must_support_only = false
# include_optional = false
# include_low_value_paths = false
# interaction_strength = 1
# include_universal_search = false

# Target FHIR server / API
# base_url = ""
# write_base_url = ""
# capability_base_url = ""
# metadata_file = ""
# fail_on_uncovered = false
# coverage_plan_path = ""
# include_cases = false

# Mock server
# mock = false
# mock_port = 0

# API / write authentication
# api_bearer_token = ""
# api_basic_username = ""
# api_basic_password = ""
# write_basic_username = ""
# write_basic_password = ""

# Generation
# exhaustive = true
# bulk_count = 25
# bulk_batch_size = 100
# bulk_pipeline_depth = 2
# concurrency = 8
# bulk_per_type_counts = []

# Validate
# profile_urls = []
# package_path = ""

# Conformance self-test
# golden_dir = ""
# conformance_out = ""
# conformance_json = false
`

// bindAllEnv registers a MOMUS_* environment variable for every config key so
// that viper.Unmarshal (which uses mapstructure and does not consult
// AutomaticEnv) still honors environment variables.
func bindAllEnv() error {
	v := reflect.ValueOf(&config{}).Elem()
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		key := t.Field(i).Tag.Get("mapstructure")
		if key == "" {
			continue
		}
		if err := viper.BindEnv(key); err != nil {
			return fmt.Errorf("bind env var for %s: %w", key, err)
		}
	}
	return nil
}

// captureFlagValues records the current cfg field value for every field whose
// CLI flag was explicitly set on the command line. These values must survive
// viper.Unmarshal so that CLI flags take precedence over the config file.
func captureFlagValues(cfg *config, cmd *cobra.Command) map[int]reflect.Value {
	captured := make(map[int]reflect.Value)
	v := reflect.ValueOf(cfg).Elem()
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		tag := t.Field(i).Tag.Get("flag")
		if tag == "" {
			continue
		}
		for _, name := range strings.Split(tag, ",") {
			if flagChanged(cmd, name) {
				captured[i] = reflect.ValueOf(v.Field(i).Interface())
				break
			}
		}
	}
	return captured
}

func restoreExplicitFlagValues(cfg *config, captured map[int]reflect.Value) {
	v := reflect.ValueOf(cfg).Elem()
	for i, val := range captured {
		v.Field(i).Set(val)
	}
}

// flagChanged reports whether the named flag was explicitly set anywhere in the
// command chain (local flags and inherited persistent flags from ancestors).
func flagChanged(cmd *cobra.Command, name string) bool {
	for c := cmd; c != nil; c = c.Parent() {
		if c.Flags().Changed(name) || c.PersistentFlags().Changed(name) {
			return true
		}
	}
	return false
}
